### ISSUE TITLE
Scoping issues in scope :o

### ISSUE THREAD

**Issue by loicteixeira** [loicteixeira/kudos#6]
Implementing a `scope` with the sugar method or the old fashion way does not give the same result.

```ruby
class Account < ActiveRecord::Base
  scope :scope_twitter_account, -> { where(type: 'TwitterAccount').first }

  def self.class_twitter_account
    where(type: 'TwitterAccount').first
  end
end

class TwitterAccount < Account
end

class GithubAccount < Account
end
```

With the `scope` method, it does two queries and returns the result of the second.
```ruby
> Account.scope_twitter_account
Account Load (0.3ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."type" = $1  ORDER BY "accounts"."id" ASC LIMIT 1  [["type", "TwitterAccount"]]
Account Load (0.4ms)  SELECT "accounts".* FROM "accounts"
[<GithubAccount:0x007fd7f785b1b0>, <TwitterAccount:0x007fd7f7887da>, <GithubAccount:0x007fd7f785a789>, ...]
```

While the `class` method, it only does one query.
```ruby
> Account.class_twitter_account
Account Load (0.5ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."type" = $1  ORDER BY "accounts"."id" ASC LIMIT 1  [["type", "TwitterAccount"]]
<TwitterAccount:0x007fd7f7887da>
 ```

I first thought it was because `first` is bound to `Account` in the former and to something else in the latter but that doesn't make sense. Can you help me clarify what's going on?

**Comment by eliotsykes** [comment]
Interesting! I'm afraid I don't know what's causing that additional query. We can debug on the call tomorrow.

**Comment by loicteixeira** [comment]
Our investigations during the call led us to realise that `scope` isn't simply `syntactic sugar` and tries to ensure a relation is always returned ([read more](https://github.com/rails/rails/issues/13647#issuecomment-203058515)).
